### PR TITLE
[3.x] Helper classes for known values

### PR DESCRIPTION
**Pull request by VictorAvelar**
This PR (based on #46) adds helper classes for known values when performing operations with Server in Laravel Forge, the main purpose of these classes is to provide a better and more user-friendly way of specifying server requirements.

There is no contributing file so please guide me through the required changes if needed, I will be more than happy to adjust the code to fit your specifications.

The additions are:
- ServerProviders: VPS providers that are supported by Laravel Forge.
- GitProviders: Git PaaS supported by Laravel Forge.
- InstallableServices: Software which versions/type can be specified when provisioning a new server (ex. PHP version to be used).

I didn't add any tests as all classes are holding constants only. 😄

Thanks for looking at my PR 🖖 

p.s. I went with the default but let me know if I should point my PR to the v2 tag.

### CODE REVIEW

**Comment by tfevens** [comment]
Perhaps the newly introduced Load Balancing methods would be applicable here as well?

**Comment by VictorAvelar** [comment]
But I think @driesvints already reviewed this one, I don't know their policy on changing a reviewed PR. Otherwise I think it is something you can add as a separate ticket.

**Comment by jbrooksuk** [comment]
@VictorAvelar if you could add the Load Balancer types, we'll review again, no problem.

**Comment by VictorAvelar** [comment]
done 😄

**Comment by taylorotwell** [comment]
Closing pending inactivity.

**Comment by VictorAvelar** [comment]
Aren't we waiting for @jbrooksuk opinion?

**Comment by driesvints** [comment]
@VictorAvelar james is with vacation now. I'll ping him once he gets back.

**Comment by jbrooksuk** [comment]
@VictorAvelar sorry for the delay!

I agree with @dri

**Comment by jbrooksuk** [comment]
@VictorAvelar sorry for the delay!

Firstly, we should make the classes non-abstract like @driesvints suggested. I think that having them as their own classes is fine, but they should maybe live within a `Resources` namespace?

**Comment by VictorAvelar** [comment]
That works for me, I will do the changes.

**Comment by driesvints** [comment]
@VictorAvelar I'm gonna close this one to keep PRs manageable but feel free to create a new one once you're ready.

**Pull request closed without merging**
