### PR TITLE
[3.x] Added syncDatabases function

### PR DESCRIPTION
**Pull request by jwktje**
A new function was added to the Forge API after I asked support about this. The turnaround on this was super quick. This is my addition to the forge-sdk to support this new endpoint. Not 100% sure if I should implement a $wait mechanism too, like when creating a database. I guess not as there is not a created resource to return. So I feel like it should be on the programmer to add sleep() in their logic if they need it (which is what I'm doing now)

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Thanks! Can you also add this to the documentation (the `README.md`).

Since this process runs asynchronously, the API does not return any result other than the request was handled.

**Comment by jwktje** [comment]
@jbrooksuk No worries. Like this you mean?

**Comment by jbrooksuk** [comment]
Great, thanks!

**Comment by jwktje** [comment]
Thanks for merging! When will this be released in a new version?

**Comment by driesvints** [comment]
Today

**Comment by tfevens** [comment]
Tuesday release day! 🥳🥳

**Pull request merged**
